import { ArrowUpRight } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useCurrency } from "../currency/useCurrency";
import { useInsights } from "../sessions/hooks";
import { changeLabel, sessionLink } from "../sessions/query";
import { Coverage, LoadError, PeriodSelect, SessionRow } from "../sessions/shared";
import { count } from "../sessions/format";
export function Insights({ period, setPeriod }: { period: string; setPeriod: (value: string) => void }) {
  const { fmt } = useCurrency(); const result = useInsights(period); const data = result.data;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-sky-700">Insights</p><h1 className="text-2xl font-semibold tracking-tight text-sky-950 sm:text-3xl">Understand the shape of your usage.</h1><p className="mt-2 text-sm text-slate-500">Compare activity and explore the sessions behind it.</p></div><PeriodSelect period={period} onChange={setPeriod} /></div>{result.isPending && <p role="status" className="text-sm text-slate-500">Calculating insights…</p>}{result.error && <LoadError error={result.error} retry={() => void result.refetch()} />}{data && <>
    <p className="text-xs text-slate-500">{new Date(data.since).toLocaleString()} – {new Date(data.until).toLocaleString()}{period !== "0" && <> · Compared with an equal elapsed interval starting {new Date(data.previous_since).toLocaleString()}</>}</p>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Indexed sessions", value: count(data.totals.sessions), current: data.totals.sessions, previous: data.previous.sessions }, { label: "Recorded events", value: count(data.totals.calls), current: data.totals.calls, previous: data.previous.calls }, { label: "Tokens, including cache", value: count(data.totals.total_tokens), current: data.totals.total_tokens, previous: data.previous.total_tokens }, { label: "Known usage value", value: fmt(data.totals.known_cost_usd), current: data.totals.known_cost_usd, previous: data.previous.known_cost_usd }].map(stat => <Card key={stat.label} className="min-w-0 gap-2 p-4"><p className="text-xs text-slate-500">{stat.label}</p><p className="break-words text-xl font-semibold tabular-nums text-sky-950">{stat.value}</p><p className="text-xs text-slate-500">{period === "0" ? "All indexed history" : changeLabel(stat.current, stat.previous)}</p></Card>)}</div>
    <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><Badge variant="secondary">Includes API estimates</Badge><span>{count(data.totals.unknown_cost_calls)} events unpriced. Some Codex models use Sol fallback rates. Subscription fees are excluded.</span><a href="#data-pricing" className="text-sky-700 underline underline-offset-4">Pricing assumptions</a></div>
    <section aria-labelledby="findings-title" className="space-y-3"><h2 id="findings-title" className="font-semibold text-sky-950">What stands out</h2>{data.findings.length ? <div className="grid gap-3 md:grid-cols-2">{data.findings.map(finding => <Card key={finding.id} className="gap-3 p-5"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-medium text-sky-950">{finding.title}</h3><Badge variant="outline" className="max-w-full whitespace-normal break-words">{finding.metric}</Badge></div><p className="text-sm leading-relaxed text-slate-600">{finding.description}</p>{finding.session_id && finding.source && <Button asChild variant="ghost" size="sm" className="-ml-3 self-start"><a href={sessionLink(finding.source, finding.session_id)}>Inspect session <ArrowUpRight className="size-4" /></a></Button>}</Card>)}</div> : <Card className="gap-2 p-5"><p className="font-medium text-slate-700">No findings for this period</p><p className="text-sm text-slate-500">More indexed activity or a wider period may reveal useful comparisons.</p></Card>}</section>
    <section aria-labelledby="top-sessions-title" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="top-sessions-title" className="font-semibold text-sky-950">Sessions to explore</h2><Button asChild variant="ghost" size="sm"><a href="#sessions">All sessions <ArrowUpRight className="size-4" /></a></Button></div><Card className="gap-0 px-4 py-1 sm:px-5">{data.top_sessions.length ? data.top_sessions.map(session => <SessionRow key={`${session.source}:${session.session_id}`} session={session} />) : <p className="py-6 text-sm text-slate-500">No attributed sessions in this period.</p>}</Card></section><Coverage unassigned={data.unassigned_events} indexedAt={data.indexed_at} />
  </>}</div>;
}
